# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- literals:
  - password=R00t
  name: mysql-root-pass
- literals:
  - username=callicoder
  - password=c@ll1c0d3r
  name: mysql-user-pass
- literals:
  - database=groupwork
  - url=jdbc:mysql://mysql:3306/groupwork?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  name: mysql-db-url
resources:
- api.yml
- frontend.yml
- ingress.yml
- api-db.yml
images:
- name: api
- name: nextjs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization